[package]
name = "sort_bench"
version = "0.1.0"
edition = "2021"

[dependencies]
icu_collator = "1.1.0"
icu = "1.1.0"
icu_testdata = "1.1.0"
glidesort = "0.1.2"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "sorts"
harness = false
